source 'https://github.com/CocoaPods/Specs.git'

target 'YSKDB', :exclusive => true do
  pod "YSKDB"
end

target 'Tests', :exclusive => true do
  pod "YSKDB"
  pod 'Specta', '~> 0.2.1'
  pod 'Expecta'
end
